export { default as communism } from "./ideologies/communism.png"
export { default as liberty } from "./ideologies/liberty.png"
export { default as globalism } from "./ideologies/globalism.png"
export { default as freemarket } from "./ideologies/freemarket.png"
export { default as nationalism } from "./ideologies/nationalism.png"
export { default as order } from "./ideologies/order.png"
export { default as environment } from "./ideologies/environment.png"
export { default as conservative } from "./ideologies/conservative.png"
export { default as double_arrow } from "./double_arrow.svg"

export { default as surprised } from "./surprised.png"

export { default as biedron } from "./candidate portraits/biedron.png"
export { default as mentzen } from "./candidate portraits/mentzen.png"
export { default as bosak } from "./candidate portraits/bosak.png"
export { default as zandberg } from "./candidate portraits/zandberg.png"
export { default as biejat } from "./candidate portraits/biejat.png"
export { default as tusk } from "./candidate portraits/tusk.png"
export { default as trzaskowski } from "./candidate portraits/trzaskowski.png"
export { default as holownia } from "./candidate portraits/holownia.png"
export { default as nawrocki } from "./candidate portraits/nawrocki.png"
export { default as braun } from "./candidate portraits/braun.png"
export { default as korwin } from "./candidate portraits/korwin.png"
export { default as maciak } from "./candidate portraits/maciak.png"
export { default as czarnek } from "./candidate portraits/czarnek.png"
export { default as morawiecki } from "./candidate portraits/morawiecki.png"

export { default as biedronImage } from "./candidate ideology images/biedron.png"
export { default as mentzenImage } from "./candidate ideology images/mentzen.png"
export { default as bosakImage } from "./candidate ideology images/bosak.png"
export { default as zandbergImage } from "./candidate ideology images/zandberg.png"
export { default as biejatImage } from "./candidate ideology images/biejat.png"
export { default as tuskImage } from "./candidate ideology images/tusk.png"
export { default as trzaskowskiImage } from "./candidate ideology images/trzaskowski.png"
export { default as holowniaImage } from "./candidate ideology images/holownia.png"
export { default as nawrockiImage } from "./candidate ideology images/nawrocki.png"
export { default as braunImage } from "./candidate ideology images/braun.png"
export { default as korwinImage } from "./candidate ideology images/korwin.png"
export { default as maciakImage } from "./candidate ideology images/maciak.png"
export { default as czarnekImage } from "./candidate ideology images/czarnek.png"
export { default as morawieckiImage } from "./candidate ideology images/morawiecki.png"
